### ISSUE TITLE
关于手机相机参数

### ISSUE THREAD

**Issue by kekedan** [wangpy1489/videoavatars_custom#1]
Hi，你好，我想问下关于手机相机参数的配置怎么可以获取到呢？这个参数的配置对于结果的影响大不大？另外论文中使用的是1080*1080的图像，但是手机拍摄的一般都不是正方向的图片，你是直接把他裁剪成1080*1080的吗？谢谢。

**Comment by wangpy1489** [comment]
可以直接裁剪，尽量保持人像在中央，否则比例可能会有变化。

**Comment by wangpy1489** [comment]
手机相机参数十分重要，关系到比例尺的转化。
一些网站上可以查到手机相机的光学元件的具体参数，比较难找，可以尝试搜索一下。

**Comment by kekedan** [comment]
> 手机相机参数十分重要，关系到比例尺的转化。
> 一些网站上可以查到手机相机的光学元件的具体参数，比较难找，可以尝试搜索一下。

谢谢~~
